apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongos-deployment
  labels:
    tier: mongo-servd
spec:
  selector:
   matchLabels:
      tier: mongo-service-deployment
  template:
    metadata:
      name: mongo-md
      labels:
        tier: mongo-service-deployment
    spec:
      containers:
      - name: mongocsss
        image: mongo
        ports:
        - containerPort: 8080
        volumeMounts:
          - name: app-data
            mountPath: /data/db
      volumes:
        - name: app-data
          persistentVolumeClaim:
            claimName: pvc1
