apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv1
  labels:
    type: storage
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1Gi
  storageClassName: standard
  hostPath:
    path: /data/pv1
